In [2]:
# your name here :)
"Jin"

'Jin'

# Quiz Python - SQL - Data analysis

## Setup & Git

### 🤔 What is a virtualenv and why is it useful?

Your answer here:

virtualenv is a tool to create isolated python environment.<br>
Useful when there is many versions of the same packages

### 🤔  How do you install a new python package? How can you later use it in your code?

Your answer here:


pip install 'name of package'

### 🤔 What are the `git` commands to use to submit new code to a central repository on GitHub? Explain each step in your own words.

Your answer here:


git add 'file path' : Tell git what file to commit <br>
git commit -m "message here" : Commit a file with a meaasage to understand which version does what<br>
git push origin master : Push/Upload to master branch

### 🤔  How would you position yourself in a parent directory in the terminal? How can you go to the `~` (home) directory?

Your answer here:


Home Directory: Type cd + press Enter in terminal<br>
Parent Directory: Type cd .. + press Enter in terminal<br>

## Python

### Lists

Given a list of numbers perform following operations:
- check how many elements does it have and store it in a `numbers_count` variable
- add a `5`
- remove the `7`

In [66]:
numbers = [-2, "2", 7, '-3']
# your code below

In [67]:
numbers_count = len(numbers)
numbers.append(5)
del numbers[2]

Now create a new list `positive_numbers` by iterating over `numbers` from previous task. It should consist of `int` only.

In [1]:
# your code below
positive_numbers = []
for number in numbers:
    if int(number)>0:
        positive_numbers.append(number)

NameError: name 'numbers' is not defined

In [72]:
positive_numbers

['2', 5]

### Functions

Create a function which will take a `list` of numbers as an argument and return the sum of positive numbers from that list (look at previous challenge). Be careful, the input list might contain both `str` and `int`!

In [74]:
# your code here
def take_list(list_number):
    sum_list = 0
    for number in list_number:
        sum_list += int(number)
    return sum_list

Call your function with `numbers` list (the one you updated) from previous challenge! Store the result in `positive_sum` variable.

In [75]:
# function call
positive_sum = take_list(positive_numbers) ; positive_sum

7

In [76]:
# the cell should output True
positive_sum == 7

True

### Calling an API

Which package do you need to call an API with Python? How do you use it? Give an example with `https://opengraph.lewagon.com/?url=https://www.lewagon.com` below and store the result in `data` variable:

In [77]:
# your code here
import requests

url = "https://opengraph.lewagon.com/"
data = requests.get(url, params={"url":"https://www.lewagon.com"})

### Code refactoring

Rewrite the following loop using `list comprehension` and store the result in `lc_uppercase_fruits` variable.

In [79]:
fruits = ['apple', 'banana', 'orange', 'strawberries', 'melon', 'pear']
uppercase_fruits = []
for fruit in fruits:
    if fruit[0] < 'n':
        uppercase_fruits.append(fruit.upper())

In [87]:
# your code here
lc_uppercase_fruits = [fruit.upper() for fruit in fruits if fruit[0] < 'n' ]

In [88]:
# the cell should output True
lc_uppercase_fruits == ["APPLE", "BANANA", "MELON"]

True

## SQL

### 🤔 What software can you use to perform some SQL queries?

Your answer here:


Dbeaver

### 🤔 How a typical SELECT query is built, with which keywords and in what order? Write some SQL boilerplate.

Your answer here:


SELECT "columns" <br>
FROM "Table" <br>

### 🤔 What is the difference between the INNER JOIN and LEFT JOIN?

Your answer here:


Inner join get the intersect(common) value from tables. <br>
Left jin get all of data in left table + the intersect value

## Data Analysis

### Create a `ndarray` of integers with 2 dimensions and store it in a `A` variable. Check how many elements it has.

In [93]:
# your code here
import numpy as np

In [95]:
A = np.array([[1,2], [3,4]]) 

In [96]:
A.size

4

### Using the same array `A`  check for the `max` elements in its rows.

In [99]:
A.max(axis = 0)

array([3, 4])

### Given the array B, select the third column of it (including all the rows). Store it in a `selection` variable.

In [100]:
B = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20]])
B

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [107]:
selection = B[ :, 2];
selection

array([ 3,  8, 13, 18])

### Using vectorial computation rewrite the loop below so that you get an array of summed rows  as result. Store it in `vectorial_sum` variable.

In [108]:
my_list = [
    [6, 5],
    [1, 3],
    [5, 6],
    [1, 4],
    [3, 7],
    [5, 8],
    [3, 5],
    [8, 4],
]

# Python way
sums = []
for row in my_list:
    sums.append(row[0] + row[1]) # standard integer "+" operator
sums

[11, 4, 11, 5, 10, 13, 8, 12]

In [120]:
# your code here, using `my_list` from previous cell
A = np.array(my_list)
np_sum = A[:,0] + A[:,1]
list(np_sum)

[11, 4, 11, 5, 10, 13, 8, 12]

### We loaded for you the `tips` dataset. What's the type of it? How can you quickly explore it?

In [111]:
import seaborn as sns
tips = sns.load_dataset('tips')

/Users/khokasai/.pyenv/versions/3.7.7/envs/lewagon/lib/python3.7/site-packages/pandas/compat/__init__.py:120: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)


In [112]:
# your answer & code here
tips.dtypes

total_bill     float64
tip            float64
sex           category
smoker        category
day           category
time          category
size             int64
dtype: object

###  How do you select the `total_bill` column? 💲💲💲

In [113]:
# your code here
tips.head() #Just checking

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [115]:
tips[["total_bill"]]

total_bill
0         16.99
1         10.34
2         21.01
3         23.68
4         24.59
..          ...
239       29.03
240       27.18
241       22.67
242       17.82
243       18.78

[244 rows x 1 columns]

### Using `boolean indexing` create a new DataFrame where the `time` is  `Dinner`. How many rows does it have?

In [119]:
# your code here
dinner = tips['time'].str.contains('Dinner')
tips[dinner].count().tip

176

### Given dataframe `a_df` and `b_df` how would you perform a `left join` with `pandas`? (not a SQL question!)

In [ ]:
# your code here
left_merged_df = a_df.merge(b_df, on='something', how='left')