In [ ]:
# your name here :)
Arron Ritchie

# Quiz Python - SQL - Data analysis

## Setup & Git

### 🤔 What is a virtualenv and why is it useful?

Your answer here:
it is a unique environment on which you can install specific versions of python (or other languages) and libraries to have the best compatibility with projects (e.g. if your company uses python 3.6) while giving you the ease of swapping to other versions with different environments


### 🤔  How do you install a new python package? How can you later use it in your code?

Your answer here:



!pip install "package name" <--- if in terminal you don't need the '!'


### 🤔 What are the `git` commands to use to submit new code to a central repository on GitHub? Explain each step in your own words.

Your answer here:


- git add 'filename' <--- this adds the specific file to a "ready to commit/push" list
- git commit -m 'your comment here' <-- this commits the files to git ready for final push with a comment for your refence
- git push origin master <--- this pushes the files to git hubs server, origin master can change depending on the git respository you are using

### 🤔  How would you position yourself in a parent directory in the terminal? How can you go to the `~` (home) directory?

Your answer here:


- .. will return you to the parent directory
- cd will return to home

## Python

### Lists

Given a list of numbers perform following operations:
- check how many elements does it have and store it in a `numbers_count` variable
- add a `5`
- remove the `7`

In [5]:
numbers = [-2, "2", 7, '-3']
# your code below
numbers_count = len(numbers)
numbers.append('5')
del numbers[2]#; numbers

[-2, '2', '-3', '5']

Now create a new list `positive_numbers` by iterating over `numbers` from previous task. It should consist of `int` only.

In [13]:
# your code below
positive_numbers = []
for num in numbers:
    positive_numbers.append(int(num))
positive_numbers

[-2, 2, -3, 5]

### Functions

Create a function which will take a `list` of numbers as an argument and return the sum of positive numbers from that list (look at previous challenge). Be careful, the input list might contain both `str` and `int`!

In [19]:
# your code here
test_list = [-2, "2", 7, '-3']

def positive_return(list):
    total = 0
    for num in list:
        if int(num) > 0:
            total += int(num)
    return total

print(positive_return(test_list))

9


Call your function with `numbers` list (the one you updated) from previous challenge! Store the result in `positive_sum` variable.

In [20]:
# function call
positive_sum = positive_return(numbers)

In [22]:
# the cell should output True
positive_sum == 7

True

### Calling an API

Which package do you need to call an API with Python? How do you use it? Give an example with `https://opengraph.lewagon.com/?url=https://www.lewagon.com` below and store the result in `data` variable:

In [29]:
# your code here
import requests
url = 'https://opengraph.lewagon.com/?url=https://www.lewagon.com'
data = requests.get(url).content
data

b'{"data":{"site_name":"Coding Bootcamp Le Wagon | Europe\'s Best Coding Bootcamp","title":"Coding Bootcamp | Le Wagon","type":"article","url":"https://www.lewagon.com/","image":"https://dwj199mwkel52.cloudfront.net/assets/core/social/home-card-3e7145382a75fc070f78c67bccd21e2fb74e4f92958c6dfdeb7a776acd499a0e.jpg","description":"Change your life, learn to code. Le Wagon is ranked as the world\'s best coding bootcamp and has enabled thousands of people to change their careers."},"url":"https://www.lewagon.com/"}'

### Code refactoring

Rewrite the following loop using `list comprehension` and store the result in `lc_uppercase_fruits` variable.

In [33]:
fruits = ['apple', 'banana', 'orange', 'strawberries', 'melon', 'pear']
uppercase_fruits = []
for fruit in fruits:
    if fruit[0] < 'n':
        uppercase_fruits.append(fruit.upper())
uppercase_fruits

['APPLE', 'BANANA', 'MELON']

In [35]:
# your code here
lc_uppercase_fruits = [fruit.upper() for fruit in fruits if fruit[0] < 'n' ]
lc_uppercase_fruits

['APPLE', 'BANANA', 'MELON']

In [36]:
# the cell should output True
lc_uppercase_fruits == ["APPLE", "BANANA", "MELON"]

True

## SQL

### 🤔 What software can you use to perform some SQL queries?

Your answer here:


DBeaver

### 🤔 How a typical SELECT query is built, with which keywords and in what order? Write some SQL boilerplate.

Your answer here:


In [ ]:
SELECT thing1, thing2
FROM table
JOIN table2

### 🤔 What is the difference between the INNER JOIN and LEFT JOIN?

Your answer here:


inner join takes the matching rows/columns from both the left and right only and left will keep all rows/columns from the left and only take matching rows/columns from the right and fill the space with NaN

## Data Analysis

### Create a `ndarray` of integers with 2 dimensions and store it in a `A` variable. Check how many elements it has.

In [44]:
# your code here
import numpy as np
a = np.ones((4,4), dtype=int)
a.size

16

### Using the same array `A`  check for the `max` elements in its rows.

In [46]:
a.ndim #answer is 2

2

### Given the array B, select the third column of it (including all the rows). Store it in a `selection` variable.

In [47]:
B = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20]])
B

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [50]:
selection = B[:,2]
selection

array([ 3,  8, 13, 18])

### Using vectorial computation rewrite the loop below so that you get an array of summed rows  as result. Store it in `vectorial_sum` variable.

In [51]:
my_list = [
    [6, 5],
    [1, 3],
    [5, 6],
    [1, 4],
    [3, 7],
    [5, 8],
    [3, 5],
    [8, 4],
]

# Python way
sums = []
for row in my_list:
    sums.append(row[0] + row[1]) # standard integer "+" operator
sums

[11, 4, 11, 5, 10, 13, 8, 12]

In [52]:
# your code here, using `my_list` from previous cell
narray = np.array(my_list)
narray

array([[6, 5],
       [1, 3],
       [5, 6],
       [1, 4],
       [3, 7],
       [5, 8],
       [3, 5],
       [8, 4]])

In [57]:
vectoral_array = narray.sum(axis=1)
vectoral_array

array([11,  4, 11,  5, 10, 13,  8, 12])

### We loaded for you the `tips` dataset. What's the type of it? How can you quickly explore it?

In [69]:
import seaborn as sns
tips = sns.load_dataset('tips')

In [59]:
# your answer & code here
tips.dtypes

total_bill     float64
tip            float64
sex           category
smoker        category
day           category
time          category
size             int64
dtype: object

In [66]:
tips.tail(5)

total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

###  How do you select the `total_bill` column? 💲💲💲

In [63]:
# your code here
tips[['total_bill']]

total_bill
0         16.99
1         10.34
2         21.01
3         23.68
4         24.59
..          ...
239       29.03
240       27.18
241       22.67
242       17.82
243       18.78

[244 rows x 1 columns]

### Using `boolean indexing` create a new DataFrame where the `time` is  `Dinner`. How many rows does it have?

In [74]:
# your code here
dinner_tips = tips[tips['time'] == 'Dinner']
dinner_tips.shape

(176, 7)

### Given dataframe `a_df` and `b_df` how would you perform a `left join` with `pandas`? (not a SQL question!)

In [ ]:
# your code here
c_df = a_df.merge(b_df, how='left', left_on='matching column', right_on='matching column')