In [3]:
import numpy as np
import pandas as pd

## Numpy

In [1]:
data_list = [
    [ 0,  1,  2,  3,  4],
    [10, 11, 12, 13, 14],
    [20, 21, 22, 23, 24],
    [30, 31, 32, 33, 34],
    [40, 41, 42, 43, 44],
]
data_np = np.array(data_list)
data_np

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [12]:
data_list[2][1:4]

[21, 22, 23]

In [21]:
[row[2] for idx, row in enumerate(data_list) if idx > 0 and idx < 4]

[12, 22, 32]

In [22]:
data_np[1:4, 2]

array([12, 22, 32])

In [26]:
A = np.arange(100)
A[1:9]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
my_list = [
    [6, 5, 5, 5, 5, 5, 5, 5],
    [1, 3, 3, 3, 3, 3, 3, 3],
    [5, 6, 6, 6, 6, 6, 6, 6],
    [1, 4, 4, 4, 4, 4, 4, 4],
    [3, 7, 7, 7, 7, 7, 7, 7],
    [5, 8, 8, 8, 8, 8, 8, 8],
    [3, 5, 5, 5, 5, 5, 5, 5],
    [8, 4, 4, 4, 4, 4, 4, 4],
]

In [31]:
A = np.array(my_list)

In [39]:
np.sum(A, axis=0)

array([32, 42])

In [38]:
np.max(A, axis=1)

array([6, 3, 6, 4, 7, 8, 5, 8])

## Pandas

In [54]:
a = pd.Series([1,2,3,4,5], index=['idx1', 'idx2', 'idx3', 'idx4', 'idx5'])
b = pd.Series([1,2,3,4,5], index=['idx1', 'idx2', 'idx3', 'idx4', 'idx6'])
pd.DataFrame({
    'a': a,
    'b': b
})

a    b
idx1  1.0  1.0
idx2  2.0  2.0
idx3  3.0  3.0
idx4  4.0  4.0
idx5  5.0  NaN
idx6  NaN  5.0

In [41]:
df = pd.read_csv('countries.csv')
df['Region'] = df['Region'].str.strip()

In [31]:
df[(df['Region'].str.contains('AMER')) | (df['Population'] > 100_000_000)]


Country                Region  Population  \
6                            Anguilla    LATIN AMER. & CARIB       13477   
7                   Antigua & Barbuda    LATIN AMER. & CARIB       69108   
8                           Argentina    LATIN AMER. & CARIB    39921833   
10                              Aruba    LATIN AMER. & CARIB       71891   
14                       Bahamas, The    LATIN AMER. & CARIB      303770   
16                         Bangladesh   ASIA (EX. NEAR EAST)   147365352   
17                           Barbados    LATIN AMER. & CARIB      279912   
20                             Belize    LATIN AMER. & CARIB      287730   
22                            Bermuda       NORTHERN AMERICA       65773   
24                            Bolivia    LATIN AMER. & CARIB     8989046   
27                             Brazil    LATIN AMER. & CARIB   188078227   
28                 British Virgin Is.    LATIN AMER. & CARIB       23098   
36                             Canada       NORTHERN AMERICA    33098932   
38                     Cayman Islands    LATIN AMER. & CARIB       45436   
41                              Chile    LATIN AMER. & CARIB    16134219   
42                              China   ASIA (EX. NEAR EAST)  1313973713   
43                           Colombia    LATIN AMER. & CARIB    43593035   
48                         Costa Rica    LATIN AMER. & CARIB     4075261   
51                               Cuba    LATIN AMER. & CARIB    11382820   
56                           Dominica    LATIN AMER. & CARIB       68910   
57                 Dominican Republic    LATIN AMER. & CARIB     9183984   
59                            Ecuador    LATIN AMER. & CARIB    13547510   
61                        El Salvador    LATIN AMER. & CARIB     6822378   
70                      French Guiana    LATIN AMER. & CARIB      199509   
80                          Greenland       NORTHERN AMERICA       56361   
81                            Grenada    LATIN AMER. & CARIB       89703   
82                         Guadeloupe    LATIN AMER. & CARIB      452776   
84                          Guatemala    LATIN AMER. & CARIB    12293545   
88                             Guyana    LATIN AMER. & CARIB      767245   
89                              Haiti    LATIN AMER. & CARIB     8308504   
90                           Honduras    LATIN AMER. & CARIB     7326496   
94                              India   ASIA (EX. NEAR EAST)  1095351995   
95                          Indonesia   ASIA (EX. NEAR EAST)   245452739   
102                           Jamaica    LATIN AMER. & CARIB     2758124   
103                             Japan   ASIA (EX. NEAR EAST)   127463611   
131                        Martinique    LATIN AMER. & CARIB      436131   
135                            Mexico    LATIN AMER. & CARIB   107449525   
140                        Montserrat    LATIN AMER. & CARIB        9439   
147              Netherlands Antilles    LATIN AMER. & CARIB      221736   
150                         Nicaragua    LATIN AMER. & CARIB     5570129   
152                           Nigeria     SUB-SAHARAN AFRICA   131859731   
156                          Pakistan   ASIA (EX. NEAR EAST)   165803560   
158                            Panama    LATIN AMER. & CARIB     3191319   
160                          Paraguay    LATIN AMER. & CARIB     6506464   
161                              Peru    LATIN AMER. & CARIB    28302603   
165                       Puerto Rico    LATIN AMER. & CARIB     3927188   
169                            Russia    C.W. OF IND. STATES   142893540   
172               Saint Kitts & Nevis    LATIN AMER. & CARIB       39129   
173                       Saint Lucia    LATIN AMER. & CARIB      168458   
174              St Pierre & Miquelon       NORTHERN AMERICA        7026   
175  Saint Vincent and the Grenadines    LATIN AMER. & CARIB      117848   
193                          Suriname    LATIN AMER. & CARIB      439117   
204

In [43]:
# df['Region'].unique()
df[df['Region'].isin(['EASTERN EUROPE', 'WESTERN EUROPE'])].head(10)

Country          Region  Population  Area (sq. mi.)  \
1                Albania   EASTERN EUROPE     3581655           28748   
4                Andorra   WESTERN EUROPE       71201             468   
12               Austria   WESTERN EUROPE     8192880           83870   
19               Belgium   WESTERN EUROPE    10379067           30528   
25  Bosnia & Herzegovina   EASTERN EUROPE     4498976           51129   
30              Bulgaria   EASTERN EUROPE     7385367          110910   
50               Croatia   EASTERN EUROPE     4494749           56542   
53        Czech Republic   EASTERN EUROPE    10235455           78866   
54               Denmark   WESTERN EUROPE     5450661           43094   
66         Faroe Islands   WESTERN EUROPE       47246            1399   

   Pop. Density (per sq. mi.) Coastline (coast/area ratio) Net migration  \
1                       124,6                         1,26         -4,93   
4                       152,1                         0,00           6,6   
12                       97,7                         0,00             2   
19                      340,0                         0,22          1,23   
25                       88,0                         0,04          0,31   
30                       66,6                         0,32         -4,58   
50                       79,5                        10,32          1,58   
53                      129,8                         0,00          0,97   
54                      126,5                        16,97          2,48   
66                       33,8                        79,84          1,41   

   Infant mortality (per 1000 births)  GDP ($ per capita) Literacy (%)  \
1                               21,52              4500.0         86,5   
4                                4,05             19000.0        100,0   
12                               4,66             30000.0         98,0   
19                               4,68             29100.0         98,0   
25                              21,05              6100.0          NaN   
30                              20,55              7600.0         98,6   
50                               6,84             10600.0         98,5   
53                               3,93             15700.0         99,9   
54                               4,56             31100.0        100,0   
66                               6,24             22000.0          NaN   

   Phones (per 1000) Arable (%) Crops (%) Other (%) Climate Birthrate  \
1               71,2      21,09      4,42     74,49       3     15,11   
4              497,2       2,22         0     97,78       3      8,71   
12             452,2      16,91      0,86     82,23       3      8,74   
19             462,6      23,28       0,4     76,32       3     10,38   
25             215,4       13,6      2,96     83,44       4      8,77   
30             336,3      40,02      1,92     58,06       3      9,65   
50             420,4      26,09      2,27     71,65     NaN      9,61   
53             314,3       39,8      3,05     57,15       3      9,02   
54             614,6      54,02      0,19     45,79       3     11,13   
66             503,8       2,14         0     97,86     NaN     14,05   

   Deathrate Agriculture Industry Service  
1       5,22       0,232    0,188   0,579  
4       6,25         NaN      NaN     NaN  
12      9,76       0,018    0,304   0,678  
19     10,27        0,01     0,24   0,749  
25      8,27       0,142    0,308    0,55  
30     14,27       0,093    0,304   0,603  
50     11,48        0,07    0,308   0,622  
53     10,59       0,034    0,393   0,573  
54     10,36       0,018    0,246   0,735  
66       8,7        0,27     0,11    0,62

In [47]:
df[~df['Region'].isin(['EASTERN EUROPE', 'WESTERN EUROPE'])].head(10)

Country                Region  Population  Area (sq. mi.)  \
0         Afghanistan   ASIA (EX. NEAR EAST)    31056997          647500   
2             Algeria        NORTHERN AFRICA    32930091         2381740   
3      American Samoa                OCEANIA       57794             199   
5              Angola     SUB-SAHARAN AFRICA    12127071         1246700   
6            Anguilla    LATIN AMER. & CARIB       13477             102   
7   Antigua & Barbuda    LATIN AMER. & CARIB       69108             443   
8           Argentina    LATIN AMER. & CARIB    39921833         2766890   
9             Armenia    C.W. OF IND. STATES     2976372           29800   
10              Aruba    LATIN AMER. & CARIB       71891             193   
11          Australia                OCEANIA    20264082         7686850   

   Pop. Density (per sq. mi.) Coastline (coast/area ratio) Net migration  \
0                        48,0                         0,00         23,06   
2                        13,8                         0,04         -0,39   
3                       290,4                        58,29        -20,71   
5                         9,7                         0,13             0   
6                       132,1                        59,80         10,76   
7                       156,0                        34,54         -6,15   
8                        14,4                         0,18          0,61   
9                        99,9                         0,00         -6,47   
10                      372,5                        35,49             0   
11                        2,6                         0,34          3,98   

   Infant mortality (per 1000 births)  GDP ($ per capita) Literacy (%)  \
0                              163,07               700.0         36,0   
2                                  31              6000.0         70,0   
3                                9,27              8000.0         97,0   
5                              191,19              1900.0         42,0   
6                               21,03              8600.0         95,0   
7                               19,46             11000.0         89,0   
8                               15,18             11200.0         97,1   
9                               23,28              3500.0         98,6   
10                               5,89             28000.0         97,0   
11                               4,69             29000.0        100,0   

   Phones (per 1000) Arable (%) Crops (%) Other (%) Climate Birthrate  \
0                3,2      12,13      0,22     87,65       1      46,6   
2               78,1       3,22      0,25     96,53       1     17,14   
3              259,5         10        15        75       2     22,46   
5                7,8       2,41      0,24     97,35     NaN     45,11   
6              460,0          0         0       100       2     14,17   
7              549,9      18,18      4,55     77,27       2     16,93   
8              220,4      12,31      0,48     87,21       3     16,73   
9              195,7      17,55       2,3     80,15       4     12,07   
10             516,1      10,53         0     89,47       2     11,03   
11             565,5       6,55      0,04     93,41       1     12,14   

   Deathrate Agriculture Industry Service  
0      20,34        0,38     0,24    0,38  
2       4,61       0,101      0,6   0,298  
3       3,27         NaN      NaN     NaN  
5       24,2       0,096    0,658   0,246  
6       5,34        0,04     0,18    0,78  
7       5,37       0,038     0,22   0,743  
8       7,55       0,095    0,358   0,547  
9       8,23       0,239    0,343   0,418  
10      6,68       0,004    0,333   0,663  
11      7,51       0,038    0,262     0,7

In [61]:
df.Country = df.Country.str.strip()
df.set_index('Country', inplace=True)

AttributeError: 'DataFrame' object has no attribute 'Country'

In [63]:
df.loc['India':'Japan', ['Region']]

Region
Country                          
India        ASIA (EX. NEAR EAST)
Indonesia    ASIA (EX. NEAR EAST)
Iran         ASIA (EX. NEAR EAST)
Iraq                    NEAR EAST
Ireland            WESTERN EUROPE
Isle of Man        WESTERN EUROPE
Israel                  NEAR EAST
Italy              WESTERN EUROPE
Jamaica       LATIN AMER. & CARIB
Japan        ASIA (EX. NEAR EAST)

In [66]:
df.sort_index(ascending=False, inplace=True)

In [79]:
df.sort_values(['Region', 'Population'], ascending=[True, False])

Region  Population  Area (sq. mi.)  \
Country                                                           
China          ASIA (EX. NEAR EAST)  1313973713         9596960   
India          ASIA (EX. NEAR EAST)  1095351995         3287590   
Indonesia      ASIA (EX. NEAR EAST)   245452739         1919440   
Pakistan       ASIA (EX. NEAR EAST)   165803560          803940   
Bangladesh     ASIA (EX. NEAR EAST)   147365352          144000   
...                             ...         ...             ...   
Faroe Islands        WESTERN EUROPE       47246            1399   
Liechtenstein        WESTERN EUROPE       33987             160   
Monaco               WESTERN EUROPE       32543               2   
San Marino           WESTERN EUROPE       29251              61   
Gibraltar            WESTERN EUROPE       27928               7   

              Pop. Density (per sq. mi.) Coastline (coast/area ratio)  \
Country                                                                 
China                              136,9                         0,15   
India                              333,2                         0,21   
Indonesia                          127,9                         2,85   
Pakistan                           206,2                         0,13   
Bangladesh                        1023,4                         0,40   
...                                  ...                          ...   
Faroe Islands                       33,8                        79,84   
Liechtenstein                      212,4                         0,00   
Monaco                           16271,5                       205,00   
San Marino                         479,5                         0,00   
Gibraltar                         3989,7                       171,43   

              Net migration Infant mortality (per 1000 births)  \
Country                                                          
China                  -0,4                              24,18   
India                 -0,07                              56,29   
Indonesia                 0                               35,6   
Pakistan              -2,77                              72,44   
Bangladesh            -0,71                               62,6   
...                     ...                                ...   
Faroe Islands          1,41                               6,24   
Liechtenstein          4,85                                4,7   
Monaco                 7,75                               5,43   
San Marino            10,98                               5,73   
Gibraltar                 0                               5,13   

               GDP ($ per capita) Literacy (%) Phones (per 1000) Arable (%)  \
Country                                                                       
China                      5000.0         90,9             266,7       15,4   
India                      2900.0         59,5              45,4       54,4   
Indonesia                  3200.0         87,9              52,0      11,32   
Pakistan                   2100.0         45,7              31,8      27,87   
Bangladesh                 1900.0         43,1               7,3      62,11   
...                           ...          ...               ...        ...   
Faroe Islands             22000.0          NaN             503,8       2,14   
Liechtenstein             25000.0        100,0             585,5         25   
Monaco                    27000.0         99,0            1035,6          0   
San Marino                34600.0         96,0             704,3      16,67   
Gibraltar                 17500.0          NaN             877,7          0   

              Crops (%) Other (%) Climate Birthrate Deathrate Agriculture  \
Country                                                                     
China              1,25     83,35     1,5     13,25      6,97       0,125   
India              2,74     42,86     2,5     22,01      8,18       0,186   
Indonesia   

In [88]:
df.groupby('Region').sum()

Population  Area (sq. mi.)  GDP ($ per capita)
Region                                                              
ASIA (EX. NEAR EAST)  3687982236        23096712            225500.0
BALTICS                  7184974          175015             33900.0
C.W. OF IND. STATES    280081548        22100843             48000.0
EASTERN EUROPE         119914717         1152222            117700.0
LATIN AMER. & CARIB    561824599        20544084            390700.0
NEAR EAST              195068377         4355586            167300.0
NORTHERN AFRICA        161407133         6018890             27300.0
NORTHERN AMERICA       331672307        21782471            130500.0
OCEANIA                 33131662         8519812            173200.0
SUB-SAHARAN AFRICA     749437000        24341406            118500.0
WESTERN EUROPE         396339998         3710478            757300.0